# Generated by Django 4.1 on 2022-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionic', '0003_alter_account_fav_question_alter_question_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='areport_notification',
            field=models.ManyToManyField(blank=True, related_name='noti_areport', to='questionic.answer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='areport_notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='qreport_notification',
            field=models.ManyToManyField(blank=True, related_name='noti_qreport', to='questionic.question'),
        ),
        migrations.AddField(
            model_name='notification',
            name='qreport_notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='rreport_notification',
            field=models.ManyToManyField(blank=True, related_name='noti_rreport', to='questionic.replyanswer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rreport_notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='faved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='fav_question',
            field=models.ManyToManyField(blank=True, related_name='fav_account', to='questionic.question'),
        ),
    ]
