# Generated by Django 4.1 on 2022-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionic', '0005_question_answer_count_alter_answer_from_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='report',
        ),
    ]
